services:
  app:
    build: .
    container_name: aitas-capstone-app
    ports:
      - "10000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
     environment:
      APP_ENV: production
      APP_KEY: ${APP_KEY}
      APP_DEBUG: false
      APP_URL: https://aitas-capstone.onrender.com
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: aitas
      DB_USERNAME: root
      DB_PASSWORD: password

  db:
    image: mysql:8.0
    container_name: aitas-capstone-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: aitas
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
